- name: "Create \"{{ tile_dir }}\" directory"
  file:
    path: "{{ tile_dir }}"
    state: directory
    mode: 0775
    owner: gis
    group: gis

- name: Start renderd
  shell: renderd --config=/etc/renderd.conf
  become: yes
  become_user: gis

- name: "Generate tiles (levels: 0-7) : World"
  shell: "render_list --map={{ style }} --tile-dir {{ tile_dir }} --num-threads={{ num_threads }} --min-zoom=0 --max-zoom=7 --all"

- name: "Generate tiles list"
  shell: /tmp/make_render_list.py > /tmp/tiles.lst

- name: "Generate tiles (levels: 7-18)"
  shell: "cat /tmp/tiles.lst | render_list --map={{ style }} --tile-dir {{ tile_dir }} --num-threads={{ num_threads }} --min-zoom=8 --max-zoom=18 --all"
