- file:
    path: /var/run/renderd
    state: directory
    mode: 0775
    owner: gis
    group: gis

- name: Install renderd configuration
  template:
    src: renderd.conf
    dest: /etc/renderd.conf

- name: Install renderd as a service
  copy:
    src: renderd.service
    dest: /etc/systemd/system/renderd.service

- systemd:
    daemon_reload: yes

- systemd:
    name: renderd
    state: started
    enabled: yes
