- name: Download OpenStretMap Carto
  include_tasks: process/openstreetmap-carto.yml

- name: Download and extract data
  include_tasks: process/extract.yml

- name: Import data in database
  include_tasks: process/import.yml
